<div>
    <div>
        <table>
            <thead>
            <tr>
              <th>id</th>
<th>name</th>
<th>created_at</th>

              <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <? foreach($this->users as $row): ?>
            <tr>
              <td><?=$row->id;?></td>
<td><?=$row->name;?></td>
<td><?=$row->created_at;?></td>

              <td>
                <a href="<?=INST_URI;?>user/delete/<?=$row->id;?>">delete</a>
                <a href="<?=INST_URI;?>user/addedit/<?=$row->id;?>">Edit</a>
              </td>
            </tr>
            <? endforeach; ?>
            </tbody>
        </table>
    </div>
    <a href="<?=INST_URI;?>user/addedit/">Add new...</a>
</div>