    <meta charset="utf-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Basilisk Project Management">
    <meta name="keywords" content="project,management">
    <meta name="theme-color" content="#ff9901">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="msapplication-starturl" content="/">

    <base href="<?=INST_URI;?>">
    <title>Basilisk</title>

    <link rel="apple-touch-icon" sizes="57x57" href="/images/logo-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/logo-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/logo-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/logo-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/logo-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/logo-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/logo-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/logo-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/logo-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/images/logo-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/logo-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/images/logo-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/logo-16x16.png">
    <link rel="manifest" href="/manifest.json">

    <script type="text/javascript">
        window.innerWidth = window.outerWidth;
    </script>

    <style type="text/css">
    /**
#27401D
#
#C0A996
**/
:root {
  --primary: #16253F;
  --primary-contrast: #ffffff;
  --primary-hover: #16253F99;
  --secondary: #182517;
  --secondary-contrast: #FAFBFC;
  --secondary-hover: #E8EBEF;
  --default: #848C41;
  --default-contrast: #FFFFFF;
  --default-hover: #99999999;
  --error: #F44336;
  --error-contrast: #FFFFFF;
  --error-hover: #F4433699;
  --success: #63AB71;
  --success-contrast: #FFFFFF;
  --success-hover: #63AB7199;
  --warning: #E09B39;
  --warning-contrast: #FFFFFF;
  --warning-hover: #E09B3999;
  --information: #51697C;
  --information-contrast: #FFFFFF;
  --information-hover: #51697C;
  --hover-opacity: 0.5;
}

@font-face {
  font-family: 'icomoon';
  font-display: swap;
  font-style: normal;
  font-weight: normal;
  src:url('/fonts/icomoon/icomoon.woff');
  src:url('/fonts/icomoon/icomoon.eot?#iefix') format('embedded-opentype'),
      url('/fonts/icomoon/icomoon.woff') format('woff'),
      url('/fonts/icomoon/icomoon.ttf') format('truetype'),
      url('/fonts/icomoon/icomoon.svg') format('svg');
}

@font-face {
    font-family: 'OpenSansRegular', sans-serif;
    font-display: swap;
    font-style: normal;
    font-weight: normal;
    src:url('/fonts/openSans/Regular/OpenSans-Regular.ttf');
    src:url('/fonts/openSans/Regular/OpenSans-Regular.otf') format('opentype'),
        url('/fonts/openSans/Regular/OpenSans-Regular.woff') format('woff'),
        url('/fonts/openSans/Regular/OpenSans-Regular.ttf') format('truetype'),
        url('/fonts/openSans/Regular/OpenSans-Regular.svg') format('svg');
}

<? readfile(INST_PATH.'app/webroot/libs/dmb-styles.css'); ?>
<? readfile(INST_PATH.'app/webroot/css/styles.css'); ?>
    </style>