    <meta charset="utf-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Basilisk Project Management">
    <meta name="keywords" content="project,management">
    <meta name="theme-color" content="#ff9901">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="msapplication-starturl" content="/">

    <base href="<?=INST_URI;?>">
    <title>Basilisk</title>

    <link rel="apple-touch-icon" sizes="57x57" href="/images/logo-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/logo-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/logo-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/logo-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/logo-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/logo-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/logo-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/logo-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/logo-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/images/logo-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/logo-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/images/logo-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/logo-16x16.png">
    <link rel="manifest" href="/manifest.json">

    <script type="text/javascript">
        window.innerWidth = window.outerWidth;
    </script>

    <style type="text/css">
<? readfile(INST_PATH.'app/webroot/libs/dmb-styles.css'); ?>
<? readfile(INST_PATH.'app/webroot/css/styles.css'); ?>
    </style>