<!doctype html>
<html lang="en">
<head>
    <? require_once(INST_PATH.'app/views/_header-contents.phtml'); ?>
</head>
<body>
    <dmb-view class="dmb-view" id="page">
        <dmb-header>
            <? if(_ACTION !== 'login'): ?>
            <dmb-menu-button menu="#general-menu" legend="Men&uacute; Principal"></dmb-menu-button>
            <? endif; ?>
            <hgroup>
                <h1 class="site-logotype"><?=SITE_NAME;?></h1>
            </hgroup>
        </dmb-header>
        <dmb-content id="page-content">
            <?=$this->yield;?>
        </dmb-content>
        <? if(_ACTION !== 'login'): ?>
        <dmb-panel id="general-menu" class="dmb-panel dmb-menu left">
            <dmb-header>
                <h3>Men&uacute;</h3>
                <dmb-close-panel orientation="left"></dmb-close-panel>
            </dmb-header>
            <dmb-content>
                <? foreach ($this->menuLinks as $entry): ?>
                    <a class="item item-main" href="<?=$entry->link;?>" target="<?=$entry->target;?>">
                        <i class="icon icon-<?=$entry->icon;?>"></i>
                        <?=$entry->label;?>
                    </a>
                    <? if ($entry->hasItems): ?>
                        <? foreach ($entry->items as $subEntry): ?>
                        <a class="item item-secondary" href="<?=$subEntry->link;?>" target="<?=$entry->target;?>">
                            <i class="icon icon-<?=$subEntry->icon;?>"></i>
                            <?=$subEntry->label;?>
                        </a>
                        <? endforeach; ?>
                    <? endif; ?>
                <? endforeach; ?>
            </dmb-content>
        </dmb-panel>
        <? endif; ?>
    </dmb-view>
    <? require_once(INST_PATH.'app/views/_footer-contents.phtml'); ?>
</body>
</html>